Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine318"
	config.vm.synced_folder = ".", "/vagrant", disabled: true

# ---- Server -----
	config.vm.define "slombardS" do |srv|
		srv.vm.hostname = "slombardS"
		srv.vm.network = "private_network", ip: "192.168.56.110"
		srv.vm.provider :libvirt do |lv|
			lv.driver = "qemu"
			lv.memory = 512
			lv.cpus = 1
		end
		srv.vm.provision "shell", path: "
