Vagrant.configure("2") do |config|
  # First Node Configuration
  config.vm.define "rpodackS" do |rpodackS|
    rpodackS.vm.provider "libvirt" do |lv|
      lv.memory = 512  # Adjust memory as needed
      lv.cpus = 1       # Adjust CPU count as needed
      # lv.disk = {
      #   size: '1024M'      # Adjust disk size if needed
      # }
    end
    rpodackS.vm.box = "generic/ubuntu2004"  # Or any Ubuntu box you prefer
    rpodackS.vm.network "private_network", ip: "192.168.121.100", bridge: "virbr1" # Example for private networking
    rpodackS.vm.provision "shell", inline: <<-SHELL
      # Add your shell commands here
      echo "Provisioning rpodackS"
      sudo apt-get update
      apt-get install -y curl sudo iptables
      curl -sfL https://get.k3s.io -o install_k3s.sh
      chmod +x install_k3s.sh
      INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-name rpodackS" ./install_k3s.sh
      nohup /usr/local/bin/k3s server --write-kubeconfig-mode 644 --node-name rpodackS >/k3s-server.log 2>&1 &
      sleep 10
      cat /var/lib/rancher/k3s/server/node-token > /node-token
    SHELL
  end


  # Second Node Configuration
  config.vm.define "rpodackSW" do |rpodackSW|
    rpodackSW.vm.provider "libvirt" do |lv|
      lv.memory = 512  # Adjust memory as needed
      lv.cpus = 1       # Adjust CPU count as needed
      # lv.disk = {
      #   size: '1024M'      # Adjust disk size if needed
      # }
    end
    rpodackSW.vm.box = "generic/ubuntu2004"  # Or any Ubuntu box you prefer
    rpodackSW.vm.network "private_network", ip: "192.168.121.101", bridge: "virbr1"  # Example for private networking
    rpodackSW.vm.provision "shell", inline: <<-SHELL
      # Add your shell commands here
      echo "Provisioning rpodackS"
      sudo apt-get update
      apt-get install -y curl sudo iptables
      curl -sfL https://get.k3s.io -o install_k3s.sh
      chmod +x install_k3s.sh
      INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-name rpodackS" ./install_k3s.sh
      nohup /usr/local/bin/k3s server --write-kubeconfig-mode 644 --node-name rpodackS >/k3s-server.log 2>&1 &
      sleep 10
      cat /var/lib/rancher/k3s/server/node-token > /node-token
    SHELL
  end
end
