# Vagrantfile
# shared libvirt network options for all private networks
NET_ADDR = "192.168.56.0/24"
NET_NAME = "vagrant56"

Vagrant.configure("2") do |config|
  # Enable synced folder for /vagrant
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

  # 1. Server
  config.vm.define "slombardS" do |server| # this is optional, if you have only 1 VM but obligatory if you have more than 
    server.vm.hostname = "slombardS"
    server.vm.box = "generic/alpine318"   # has libvirt builds available
    server.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: NET_NAME,
      libvirt__network_address: NET_ADDR,
      libvirt__dhcp_enabled: false
    server.vm.provider :libvirt do |lv|
      lv.memory = 512
      lv.cpus   = 1

      lv.cpu_mode = "host-passthrough"
    end

  end
  
  # 1. Worker
  config.vm.define "slombardSW" do |worker| # this is optional, if you have only 1 VM but obligatory if you have more than 
    worker.vm.hostname = "slombardSW"
    worker.vm.box = "generic/alpine318"   # has libvirt builds available
    worker.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name: NET_NAME,
      libvirt__network_address: NET_ADDR,
      libvirt__dhcp_enabled: false
    worker.vm.provider :libvirt do |lv|
      lv.memory = 512
      lv.cpus   = 1

      lv.cpu_mode = "host-passthrough"
    end
  end

  # Ansible provisioning runs after both VMs are up
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "confs/ansible/playbook.yml"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end

