# Vagrantfile
Vagrant.configure("2") do |config|
  # shared libvirt network options for all private networks
  NET_ADDR = "192.168.56.0/24"
  NET_NAME = "vagrant56"
  # 1. Server
  config.vm.define "server" do |server| # this is opitional, if you have only 1 VM but oblicatory if you have more than 
    server.vm.box = "generic/alpine318"   # has libvirt builds available
    server.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: NET_NAME,
      libvirt__network_address: NET_ADDR,
      libvirt__dhcp_enabled: false
    server.vm.provider :libvirt do |lv|
      lv.memory = 512
      lv.cpus   = 1

      lv.cpu_mode = "host-passthrough"
    end

  # keep it tiny; rsync will handle /vagrant by default on libvirt
    server.vm.provision "shell", inline: <<-SHELL
      set -e
      apk update
      apk add --no-cache vim curl qemu-guest-agent
      rc-update add qemu-guest-agent
      rc-service qemu-guest-agent start
      echo "Server ready."
      SHELL
    end
  
  # 1. Worker
  config.vm.define "worker" do |worker| # this is opitional, if you have only 1 VM but oblicatory if you have more than 
    worker.vm.box = "generic/alpine318"   # has libvirt builds available
    worker.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name: NET_NAME,
      libvirt__network_address: NET_ADDR,
      libvirt__dhcp_enabled: false
    worker.vm.provider :libvirt do |lv|
      lv.memory = 512
      lv.cpus   = 1

      lv.cpu_mode = "host-passthrough"
    end

  # keep it tiny; rsync will handle /vagrant by default on libvirt
    worker.vm.provision "shell", inline: <<-SHELL
      set -e
      apk update
      apk add --no-cache vim curl qemu-guest-agent
      rc-update add qemu-guest-agent
      rc-service qemu-guest-agent start
      echo "Server ready."
      SHELL
    end
end

